

function changeTextEMS() {
    jsCovArea.style.display = 'none';
    jsQuote.style.display = 'none';
    jsOverview.style.display = 'block';
    jsOverview.innerHTML = '<h1>What is E.M.S?</h1> <br /> <p>An EMS or Building Management System (BMS) as it is also called, is a computer-based control system installed in buildings that controls and monitors its mechanical and electrical equipment, such as ventilation, lighting, power systems, fire systems, and security systems. One of the primary objectives of a BMS is to reduce costs through improved operational and energy efficiency, among other uses, including:<br /><br />• Control of internal comfort conditions<br />• Individual room or office control<br />• Effective proactive monitoring and targeting of energy consumption<br />•	Improved reliability and life of mechanical systems<br />• Effective response to HVAC-related complaints<br /><br />A traditional BMS consists of software and hardware; the software program is usually configured in a hierarchical manner with multiple levels of networks and is typically proprietary. All BMS systems integrate Internet protocols and open standards such as BACnet (Building Automation Control network), LON (local operating networks) and Modbus, which allow standardized communications between building automation devices from different hardware manufacturers. These systems are mainly custom and are installed in a office buildings, campus type universities, etc.<br />One of the largest benefits that Cutting Edge is known for is selecting the right system for the customer. Many companies purchase an EMS/BMS system that is overkill for their facility and usually is disconnected or override within several years and turns out to be a waste of money.<br />Cutting Edge’s Energy Management and Building Controls Systems & Services Solution assists companies select the right system for their operation. From a single location to multi-site, multi-state facilities―with designing and implementing energy management and building controls systems, including engineering, installation, commissioning and system maintenance, as well as overall project management.<br />I enjoy the challenge of working with clients to make sure that they are installing the right system for their needs and more importanly use the data to make informed decisions. It’s a great reward to see the benefit and value the client receives.<br />Please contact us with any questions or for assistance in creating a EMS / BMS that’s right for you.</p>';
}

function changeTextCount() {
    jsCovArea.style.display = 'none';
    jsQuote.style.display = 'none';
    jsOverview.style.display = 'block';
    jsOverview.innerHTML = '<h1>Count on Cutting Edge Lighting Solutions</h1><br /><p></p>'